debezium.sink.type=kafka
debezium.sink.kafka.producer.bootstrap.servers=kafka:29092
debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer

debezium.format.key.schemas.enable=false
debezium.format.value.schemas.enable=false
debezium.format.value=json
debezium.format.key=json

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=user
debezium.source.database.password=password
debezium.source.database.dbname=database
debezium.source.topic.prefix=cdc
debezium.source.table.include.list=public.users
debezium.source.plugin.name=pgoutput
debezium.source.snapshot.mode=no_data

debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat